config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :railsfriends
  get 'home/index'
  get 'home/about'
  get 'home/contact1'
  #get 'contact1'
  #root 'home#index' #localhost:3000
  root 'railsfriends#index'
  #get '*home', to: 'home#index', format: true
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/railsfriend.rb
class Railsfriend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :railsfriends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My Name is John Elder...."
    @answer = 2 + 2
  end

  def contact
  end



end

app/controllers/railsfriends_controller.rb
class RailsfriendsController < ApplicationController
  before_action :set_railsfriend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /railsfriends or /railsfriends.json
  def index
    @railsfriends = Railsfriend.all
  end

  # GET /railsfriends/1 or /railsfriends/1.json
  def show
  end

  # GET /railsfriends/new
  def new
   # @railsfriend = Railsfriend.new
    @railsfriend = current_user.railsfriends.build
    
  end

  # GET /railsfriends/1/edit
  def edit
  end

  # POST /railsfriends or /railsfriends.json
  def create
    #@railsfriend = Railsfriend.new(railsfriend_params)
     @railsfriend = current_user.railsfriends.build(railsfriend_params)

    respond_to do |format|
      if @railsfriend.save
        format.html { redirect_to @railsfriend, notice: "Railsfriend was successfully created." }
        format.json { render :show, status: :created, location: @railsfriend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @railsfriend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railsfriends/1 or /railsfriends/1.json
  def update
    respond_to do |format|
      if @railsfriend.update(railsfriend_params)
        format.html { redirect_to @railsfriend, notice: "Railsfriend was successfully updated." }
        format.json { render :show, status: :ok, location: @railsfriend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @railsfriend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railsfriends/1 or /railsfriends/1.json
  def destroy
    @railsfriend.destroy
    respond_to do |format|
      format.html { redirect_to railsfriends_url, notice: "Railsfriend was successfully destroyed." }
      format.json { head :no_content }
    end 
  end

  def correct_user

     @railsfriend = current_user.railsfriends.find_by(id: params[:id])
     redirect_to railsfriends_path, notice: "Not Authorized to Edit This Friend" if @railsfriend.nil?
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railsfriend
      @railsfriend = Railsfriend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def railsfriend_params
      params.require(:railsfriend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/railsfriends_helper.rb
module RailsfriendsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App',root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
          
        </li>

        
        

      <% if user_signed_in? %>

      <li class="nav-item">
          <%= link_to "Add Friend", new_railsfriend_path, class:"nav-link" %>
          
        </li>

      <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          
        </li>

        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          
        </li>
        <% end %>
        


        <li class="nav-item">
          <%= link_to "Contact", home_contact1_path, class:"nav-link" %>
          
        </li>

        

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

<p>

	<%= @about_me %>
</p>

<p>
	2 + 2 =<%= @answer %>
</p>

<p>
	

	<% answer = 2 + 3 %>

	2 + 3 = <%= answer %>
</p>

app/views/home/contact.html.erb
<h1>Hello </h1>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first webpage...

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Friend App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>

      <%= render 'layouts/alerts' %>
      <% end %>
      <br/>
        <%= yield %>
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/railsfriends/_form.html.erb
<%= form_with(model: railsfriend) do |form| %>
  <% if railsfriend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(railsfriend.errors.count, "error") %> prohibited this railsfriend from being saved:</h2>

      <ul>
        <% railsfriend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <br/>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <br/>
    <%= form.text_field :email, class:"form-control" , placeholder:"Email"%>
  </div>

  <div class="field form-group">
    <br/>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  
<div class="field form-group">
    <br/>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div class="field form-group">
    <br/>
    <%= form.number_field :user_id, id: :railsfriend_user_id, class:"form-control", value: current_user.id , type: :hidden%>
  </div>
  
  
  <div class="actions">
    <br/>
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/railsfriends/edit.html.erb
<h1>Editing Railsfriend</h1>
<br/>
<%= render 'form', railsfriend: @railsfriend %>
<br/>
<%= link_to 'Show', @railsfriend, class:"btn btn-secondary" %> 

<%= link_to 'Delete', @railsfriend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

<%= link_to 'Back', railsfriends_path, class:"btn btn-dark" %>

app/views/railsfriends/index.html.erb
<% if user_signed_in? %>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @railsfriends.each do |railsfriend| %>
    <% if railsfriend.user == current_user %>
      <tr>
        <td>
          <%= link_to railsfriend.first_name + ' ' + railsfriend.last_name, railsfriend %>
        </td>
        <td><%= railsfriend.email %></td>
        <td><%= railsfriend.phone %></td>
        <td><%= railsfriend.twitter %></td>
        
        

        
        
        <td><%= link_to 'Delete', railsfriend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
       
        
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railsfriend', new_railsfriend_path, class:"btn btn-secondary" %>
<% else %>

<h1>Hello World</h1>
This is my first webpage...

<% end %>

app/views/railsfriends/new.html.erb
<h1>Add New Friend</h1>
<br/>
<%= render 'form', railsfriend: @railsfriend %>
<br/>
<%= link_to 'Back', railsfriends_path, class:"btn btn-dark" %>

app/views/railsfriends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @railsfriend.first_name %>
    <%= @railsfriend.last_name %>
  </h1>
  <p class="lead">
    <%= @railsfriend.email %>   |
  <%= @railsfriend.phone %>   |
  <%= @railsfriend.twitter %>
  </p>
  <br/>
  <%= link_to 'Edit', edit_railsfriend_path(@railsfriend), class:"btn btn-secondary" %> 

  <%= link_to 'Delete', @railsfriend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  
<%= link_to 'Back', railsfriends_path, class:"btn btn-dark" %>
</div>